version: '2'

services:

    master:
        image: sixeyed/hadoop-dotnet:2.7.2
        ports: 
            - "50070:50070"
            - "8088:8088"
        command: master
        hostname: hadoop-dotnet-master
        container_name: hadoop-dotnet-master

    worker-1:
        image: sixeyed/hadoop-dotnet:2.7.2
        command: worker
        ports:
            - "50075"
            - "8142:8042"
            - "19888:19888"
        links:
            - master:hadoop-dotnet-master
        hostname: hadoop-dotnet-worker-1
        container_name: hadoop-dotnet-worker-1

    worker-2:
        image: sixeyed/hadoop-dotnet:2.7.2
        command: worker
        ports:
            - "50075"
            - "8242:8042"
            - "29888:19888"
        links:
            - master:hadoop-dotnet-master
        hostname: hadoop-dotnet-worker-2
        container_name: hadoop-dotnet-worker-2

    worker-3:
        image: sixeyed/hadoop-dotnet:2.7.2
        command: worker
        ports:
            - "50075"
            - "8342:8042"
            - "39888:19888"
        links:
            - master:hadoop-dotnet-master
        hostname: hadoop-dotnet-worker-3
        container_name: hadoop-dotnet-worker-3

    worker-4:
        image: sixeyed/hadoop-dotnet:2.7.2
        command: worker
        ports:
            - "50075"
            - "8442:8042"
            - "49888:19888"
        links:
            - master:hadoop-dotnet-master
        hostname: hadoop-dotnet-worker-4
        container_name: hadoop-dotnet-worker-4